# Generated by Django 4.2.1 on 2023-12-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_remove_sector_user_user_sectors_alter_sector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, to='sectors.sector'),
        ),
    ]
