# Generated by Django 4.2.1 on 2023-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_alter_user_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sectors',
            field=models.ManyToManyField(to='sectors.sector'),
        ),
    ]
